# config/auth.yaml
aws_cognito:
  user_pool_id: "eu-west-1_O9xcPaG24"
  client_id: "4ffgfe9g364gep939ip6bj72u5"
  region: "eu-west-1"
  auth_url: "https://cognito-idp.eu-west-1.amazonaws.com/"
credentials:
  username: "naistro"
  password: "test123ABC!"
aws:
  access_key_id: "AKIAXWDVRBNDUPHKEDGB"
  secret_access_key: "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"
headers:
  content_type: "application/x-amz-json-1.1"
