aws_cognito:
  user_pool_id: "eu-west-1_O9xcPaG24"
  client_id: "4ffgfe9g364gep939ip6bj72u5"
  region: "eu-west-1"
  auth_url: "https://cognito-idp.eu-west-1.amazonaws.com/"
credentials:
  username: "your-username"
  password: "your-password"
headers:
  content_type: "application/x-amz-json-1.1"
  